name: BackendTest

on:
  push:
    branches: dev
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install java 13
      run: |
          sudo apt install -y curl
          curl -O https://download.java.net/java/GA/jdk13/5b8a42f3905b406298b72d750b6919f6/33/GPL/openjdk-13_linux-x64_bin.tar.gz
          tar xvf openjdk-13_linux-x64_bin.tar.gz
          sudo mv jdk-13 /opt/
          sudo tee /etc/profile.d/jdk13.sh <<EOF
          export JAVA_HOME=/opt/jdk-13
          export PATH=\$PATH:\$JAVA_HOME/bin
          EOF
          source /etc/profile.d/jdk13.sh
    - name: change dir
      # Also make gradlew an executable in case someone did something dumb
      run: |
        cd Server/
        chmod +x ./gradlew
    - name: build server
      run: ./gradlew build
    - name: switch back dir
      run: cd .. # this might help
    - name: Heroku Deploy
      uses: AkhileshNS/heroku-deploy@v3.0.0
      with:
        # This will be used for authentication. You can find it in your heroku homepage account settings
        heroku_api_key: 954c8833-4b96-41ac-b091-e2bd9f42dc18
        # Email that you use with heroku
        heroku_email: justin.tremblay@mail.mcgill.ca
        # The appname to use for deploying/updating
        heroku_app_name: fitboi-dev
        # The branch that you would like to deploy to Heroku
        branch: dev
