name: BackendTest

on:
  push:
    branches: dev
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: install java 13
      run: |
          sudo apt install -y curl
          curl -O https://download.java.net/java/GA/jdk13/5b8a42f3905b406298b72d750b6919f6/33/GPL/openjdk-13_linux-x64_bin.tar.gz
          tar xvf openjdk-13_linux-x64_bin.tar.gz
          sudo mv jdk-13 /opt/
          sudo tee /etc/profile.d/jdk13.sh <<EOF
          export JAVA_HOME=/opt/jdk-13
          export PATH=\$PATH:\$JAVA_HOME/bin
          EOF
          source /etc/profile.d/jdk13.sh
    - name: change dir
      run: cd Server/
    - name: build server
      run: ./gradlew build
    - name: run unit tests
      run: ./gradlew test
